### ISSUE TITLE
Feat: 메인 화면 구현, 전체목록 화면 연결

### ISSUE THREAD

**Issue by dev-junehee** [dev-junehee/haeyazi#10]
##  📌 Overview
- 메인 화면 UI를 구현합니다.
- 메인 화면에서 전체목록 화면을 연결합니다.

<br />

## ✔️ Todo
- [x] 메인 화면 UI 구현
- [x] 전체목록 화면 연결
- [x] 할 일 추가 화면 기존 연결 삭제/메인 화면에 재연결 (ToolBar)

<br />

## 🔗 References
- [layoutSubviews(), draw() 는 언제 사용할까? 뷰를 업데이트 하고싶을 때 원리.](https://velog.io/@dodo_dev/layoutSubviews-draw-는-언제-사용할까-뷰가-화면에-그려지는-원리)
- [[iOS] - UIToolBar 코드로 작성하기](https://velog.io/@sun02/iOS-UIToolBar-코드로-작성하기)
